#Author: janura@amazon.com Servicenow ticket creation Lambda

service: snow-202502022023

frameworkVersion: ">=1.1.0 <=3.27.0"

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  stage: snowdev
  region: us-east-2
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: "*"
          
functions:
  snowticketfunc:
    handler: api/snowticket.create
    memorySize: 512
    description: Create servicenow ticket
    events:
      - http: 
          path: create
          method: post
  
 
 